spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-enums-package: com.zhixing.system.pojo
  configuration:
    map-underscore-to-camel-case: false